// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xjvinkcrnfffunyoykzs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhqdmlua2NybmZmZnVueW95a3pzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0OTIyODYsImV4cCI6MjA3MzA2ODI4Nn0.sBHXVr3EmQtQUlxoED-Xb2IZOToCumfnCFhK8UbJFMI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});